/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LobbyView.java
 *
 * Created on 2010-01-22, 01:51:24
 */

package ShipsClient;
import Basics.ShipsProtocol;
import java.net.*;
import java.io.*;
import javax.swing.*;
/**
 *
 * @author bigfun
 */
public class LobbyView extends javax.swing.JFrame implements ConnActionListener {

    PrintWriter out;
    Socket socket;
    /** Creates new form LobbyView */
    public LobbyView(Socket socket, String nickname) {
        this.socket = socket;
                if (socket != null) {
            try {
                out = new PrintWriter(new BufferedWriter(new OutputStreamWriter(socket.getOutputStream())), true);
            } catch (IOException ex) {
            }
        }

        out.println(ShipsProtocol.LOBBY_REGISTER_ + nickname);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listUsers = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        listGames = new javax.swing.JList();
        txtMessage = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtChat = new javax.swing.JTextArea();
        btnSend = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        btnJoin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        listUsers.setBorder(javax.swing.BorderFactory.createTitledBorder("Użytkownicy"));
        listUsers.setName("listUsers"); // NOI18N
        jScrollPane1.setViewportView(listUsers);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        listGames.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista Gier"));
        listGames.setName("listGames"); // NOI18N
        jScrollPane2.setViewportView(listGames);

        txtMessage.setBorder(null);
        txtMessage.setName("txtMessage"); // NOI18N
        txtMessage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMessageKeyPressed(evt);
            }
        });

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        txtChat.setColumns(20);
        txtChat.setEditable(false);
        txtChat.setRows(5);
        txtChat.setBorder(javax.swing.BorderFactory.createTitledBorder("Chat"));
        txtChat.setName("txtChat"); // NOI18N
        jScrollPane3.setViewportView(txtChat);

        btnSend.setText("Wyślij");
        btnSend.setBorder(null);
        btnSend.setName("btnSend"); // NOI18N

        btnCreate.setText("Stwórz grę");
        btnCreate.setName("btnCreate"); // NOI18N

        btnJoin.setText("Dołącz");
        btnJoin.setName("btnJoin"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnJoin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSend, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCreate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnJoin))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSend)
                    .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnSend, txtMessage});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMessageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMessageKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER && !txtMessage.getText().isEmpty())
        {
            out.println(ShipsProtocol.LOBBY_SEND_MESSAGE_ + txtMessage.getText());
            txtMessage.setText("");
        }

    }//GEN-LAST:event_txtMessageKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnJoin;
    private javax.swing.JButton btnSend;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList listGames;
    private javax.swing.JList listUsers;
    private javax.swing.JTextArea txtChat;
    private javax.swing.JTextField txtMessage;
    // End of variables declaration//GEN-END:variables

    public void connActionPerformed(String message) {
        if (message.startsWith(ShipsProtocol.LOBBY_NEW_MESSAGE_))
        {
            String[] list = message.split(":", 4);
            if (list.length > 3)
            {
                addMessage("<" + list[2] + "> " + list[3]+"\n");
            }
            return;
        }
        if (message.startsWith(ShipsProtocol.LOBBY_NEW_PLAYER_))
        {
            String[] list = message.split(":", 3);
            if (list.length > 2)
            {
                addMessage("[INFO]: User " + list[2] + " joined!\n");
                listUsers.add(list[2], this);
            }
        }
    }
        private void addMessage(String msg) {
        txtChat.append(msg);
        txtChat.setCaretPosition(txtChat.getText().length());

    }

}
